// Constants
export const DAILY_CAPACITY = 792;
export const MIN_AVAILABLE_FOR_ORDER = 6;
export const MAX_FLAVOR_EXCLUSIONS = 3; // Maximum flavors a customer can exclude

// Box Sizes Configuration
export const BOX_SIZES = [
  { pieces: 6, price: 25, label: "6 pcs", maxExclusions: 3, regionRestricted: true },
  { pieces: 12, price: 50, label: "12 pcs", maxExclusions: 3, regionRestricted: true },
  { pieces: 24, price: 95, label: "24 pcs", maxExclusions: 3, regionRestricted: false },
  { pieces: 36, price: 135, label: "36 pcs", bestSeller: true, maxExclusions: 3, regionRestricted: false },
];

// Flavors Configuration
export const FLAVORS = [
  { name: "Chewing-gum", nameAr: "علكة", color: "320 75% 75%" },
  { name: "Citron", nameAr: "ليمون", color: "52 90% 70%" },
  { name: "Fraise", nameAr: "فراولة", color: "350 85% 75%" },
  { name: "Pêche", nameAr: "خوخ", color: "25 90% 75%" },
  { name: "Chocolat", nameAr: "شوكولاتة", color: "25 45% 45%" },
  { name: "Orange", nameAr: "برتقال", color: "30 95% 65%" },
  { name: "Framboise", nameAr: "توت العليق", color: "340 85% 70%" },
  { name: "Vanille", nameAr: "فانيليا", color: "45 30% 85%" },
  { name: "Pistache", nameAr: "فستق", color: "100 40% 65%" },
  { name: "Caramel", nameAr: "كراميل", color: "35 60% 60%" },
  { name: "Café", nameAr: "قهوة", color: "30 30% 40%" },
  { name: "Abricot", nameAr: "مشمش", color: "28 80% 70%" },
];

// Cities Configuration with Delivery Info
export const CITIES = [
  { name: "Agadir", nameAr: "أكادير", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Agourai", nameAr: "أغوراي", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Ain Aicha", nameAr: "عين عائشة", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Ain Atiq", nameAr: "عين عتيق", deliveryHours: 24, inSaleRabatRegion: true, deliveryPrice: 40 },
  { name: "Ain baida", nameAr: "عين بايدا", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Ain Cheggag", nameAr: "عين الشڭڭاغ", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Ain Chekaf - Fes", nameAr: "عين شيكاف - فيس", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "AIn El Aouda", nameAr: "عين ال اودا", deliveryHours: 24, inSaleRabatRegion: true, deliveryPrice: 40 },
  { name: "Ain Harouda casa", nameAr: "عين هارودا كاسا", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Ain Jiri - Meknes", nameAr: "عين جيري - ميكنيس", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Ain Kansara", nameAr: "عين الكنسرة", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Ain leuh", nameAr: "عين ليوه", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Ain Mediouna - Taounate", nameAr: "عين مديونة - تاونات", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Ait Belkacem", nameAr: "ايت بيلكاكيم", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Ait melloul", nameAr: "ايت ميللول", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Ajdir", nameAr: "اجدير", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Aknoul", nameAr: "اكنول", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Al Hoceima", nameAr: "الحسيمة", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Anza -AGADIR", nameAr: "انزا - اݣادير", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "AOURIR", nameAr: "اورير", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Azilal", nameAr: "أزيلال", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Azrou", nameAr: "ازرو", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "azrou", nameAr: "ازرو", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "beni mellal", nameAr: "بني ميللال", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Benslimane", nameAr: "بينسليماني", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Berkane", nameAr: "بركان", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Bouderbala", nameAr: "بوديربالا", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Boufakrane", nameAr: "بوفاكراني", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Bouknadel", nameAr: "بوكناديل", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 25 },
  { name: "Boulmane", nameAr: "بولماني", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Bouznika", nameAr: "بوزنيقة", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Cabo Negro", nameAr: "كابو نيݣرو", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "casablanca", nameAr: "كاسابلانكا", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Chefchaouen", nameAr: "شفشاون", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Deroua", nameAr: "ديروا", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Diabat", nameAr: "ديابات", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "EL BARAKA - MEKNES", nameAr: "ال باراكا - ميكنيس", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "El-ouidane (MARRAKECH)", nameAr: "ال - ويداني (مارراكيش)", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Eljadida", nameAr: "يلجاديدا", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Eloualidia -eljadida", nameAr: "يلواليديا - يلجاديدا", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Essaouira", nameAr: "الصويرة", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Fes", nameAr: "فاس", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Fnideq", nameAr: "الفنيدق", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Fquih Ben Salah", nameAr: "فقويه بن سالاه", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Ghazoua", nameAr: "غازوا", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "had draa", nameAr: "هاد دراا", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "had ouled fraj", nameAr: "هاد أولاد فراج", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "HANCHANE-ESSA", nameAr: "هانشاني - يسسا", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Harhoura", nameAr: "الهرهورة", deliveryHours: 24, inSaleRabatRegion: true, deliveryPrice: 30 },
  { name: "Ifrane", nameAr: "إفران", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Ifrn atlas saghir", nameAr: "يفرن اتلاس ساغير", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Inzegane", nameAr: "إنزكان", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Jamaat shaim", nameAr: "جاماات سهايم", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "JORF LASFAR", nameAr: "جورف لاسفار", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "kenitra", nameAr: "كينيترا", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 30 },
  { name: "Khemissat", nameAr: "خيميسسات", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "KHENIFRA zone bni mallal", nameAr: "خينيفرا زوني بني ماللال", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Ksar El Kebir", nameAr: "القصر الكبير", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Ksar Seghir", nameAr: "كسار سيغير", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Larache", nameAr: "العرائش", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Maaziz", nameAr: "ماازيز", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Marrakech", nameAr: "مراكش", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Martil", nameAr: "مرتيل", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "MEJJAT - Meknes", nameAr: "ميججات - ميكنيس", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Mejji-essaouira", nameAr: "ميججي - يسساويرا", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Meknes", nameAr: "مكناس", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Mernissa", nameAr: "ميرنيسسا", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Missour", nameAr: "ميسسور", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Mograne -KENITRA", nameAr: "موݣراني - كينيترا", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 25 },
  { name: "Moulay Bousselham", nameAr: "مولاي بوسسيلهام", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Moulay Idriss Zerhoun", nameAr: "مولاي يدريسس زيرهون", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "MOULAY YAACOUB", nameAr: "مولاي يااكوب", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Ouazzane", nameAr: "واززاني", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Oued Amlil", nameAr: "ويد امليل", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Ouisslan", nameAr: "ويسسلان", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Oulad Tayeb - Fes", nameAr: "أولاد تاييب - فيس", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "OULMES", nameAr: "ولميس", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Ounagha", nameAr: "وناغا", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Outat el Haj", nameAr: "وتات ال هاج", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "RABAT", nameAr: "رابات", deliveryHours: 24, inSaleRabatRegion: true, deliveryPrice: 25 },
  { name: "rahma", nameAr: "راهما", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Ras El Ma-FES", nameAr: "راس ال ما - فيس", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Ribate El Kheir", nameAr: "ريباتي ال خيير", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Romani", nameAr: "روماني", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Safi", nameAr: "آسفي", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Sahel Boutaher - Taounate", nameAr: "ساهيل بوتاهير - تاوناتي", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Sala Al jadida", nameAr: "سالا ال جاديدا", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 20 },
  { name: "Sale", nameAr: "سلا", deliveryHours: 24, inSaleRabatRegion: true, deliveryPrice: 20 },
  { name: "Sebt Gzoula", nameAr: "سيبت ݣزولا", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Sebt Mtiwa", nameAr: "سيبت متيوا", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Sefrou", nameAr: "صفرو", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Senhaja - Sefrou", nameAr: "سينهاجا - سيفرو", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Settat", nameAr: "سطات", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "sidi addi", nameAr: "سيدي اددي", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Sidi allal bahraoui", nameAr: "سيدي اللال باهراوي", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Sidi Bouzid", nameAr: "سيدي بوزيد", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "SIDI HRAZEM", nameAr: "سيدي هرازيم", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Sidi kacem", nameAr: "سيدي كاكيم", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Sidi rahal -CASA", nameAr: "سيدي راهال - كاسا", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Skhirat", nameAr: "سخيرات", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 30 },
  { name: "Smimou", nameAr: "سميمو", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Soualem", nameAr: "سواليم", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "SOUK EL GOUR", nameAr: "سوك ال ݣور", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Taddart - Taza", nameAr: "تاددارت - تازا", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Taghazout", nameAr: "تاغازوت", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Tahla zone fes", nameAr: "تاهلا زوني فيس", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "TAMANAR zone el jadida", nameAr: "تامانار زوني ال جاديدا", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Tamaris", nameAr: "تاماريس", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Tamesna", nameAr: "تامسنا", deliveryHours: 24, inSaleRabatRegion: true, deliveryPrice: 40 },
  { name: "Tanger", nameAr: "طنجة", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Taounate", nameAr: "تاونات", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Taza", nameAr: "تازة", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Temara", nameAr: "تمارة", deliveryHours: 24, inSaleRabatRegion: true, deliveryPrice: 25 },
  { name: "Tetouan", nameAr: "تطوان", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Thar Es-Souk", nameAr: "تهار يس - سوك", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Tiddas", nameAr: "تيدداس", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Tiflet", nameAr: "تيفليت", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Tit mellil", nameAr: "تيت ميلليل", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Tizi Ouasli", nameAr: "تيزي واسلي", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Youssoufia", nameAr: "اليوسفية", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Zrizer", nameAr: "زريزير", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Ain taoujdate", nameAr: "عين تاوجداتي", deliveryHours: 48, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Dakhla", nameAr: "الداخلة", deliveryHours: 48, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Guelmim", nameAr: "كلميم", deliveryHours: 48, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Laayoun", nameAr: "العيون", deliveryHours: 48, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Merzouga", nameAr: "ميرزوݣا", deliveryHours: 48, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Midelt", nameAr: "ميدلت", deliveryHours: 48, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Nador", nameAr: "الناظور", deliveryHours: 48, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Ouarzazate", nameAr: "ورزازات", deliveryHours: 48, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Oujda", nameAr: "وجدة", deliveryHours: 48, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "SAAIDIA zone oujda", nameAr: "ساايديا زوني وجدا", deliveryHours: 48, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Tan-Tan", nameAr: "طانطان", deliveryHours: 48, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Tiznit zone agadir", nameAr: "تيزنيت زوني اݣادير", deliveryHours: 48, inSaleRabatRegion: false, deliveryPrice: 45 },
  { name: "Zagora", nameAr: "زاكورة", deliveryHours: 48, inSaleRabatRegion: false, deliveryPrice: 45 },
];

// Helper function to get city by name
export const getCityByName = (cityName) => {
  return CITIES.find(city => city.name === cityName);
};

// Helper function to get box size configuration
export const getBoxSize = (pieces) => {
  return BOX_SIZES.find(box => box.pieces === pieces);
};

// Helper function to get flavor by name
export const getFlavorByName = (flavorName) => {
  return FLAVORS.find(flavor => flavor.name === flavorName);
};

// Helper function to get included flavors from excluded list
export const getIncludedFlavors = (excludedFlavors = []) => {
  return FLAVORS.filter(flavor => !excludedFlavors.includes(flavor.name));
};