// Constants
export const DAILY_CAPACITY = 648;
export const MIN_AVAILABLE_FOR_ORDER = 6;

// Box Sizes Configuration
export const BOX_SIZES = [
  { pieces: 6, price: 25, label: "6 pcs", maxFlavors: 0, regionRestricted: true },
  { pieces: 12, price: 50, label: "12 pcs", maxFlavors: 0, regionRestricted: true },
  { pieces: 24, price: 95, label: "24 pcs", maxFlavors: 6, regionRestricted: false },
  { pieces: 36, price: 135, label: "36 pcs", bestSeller: true, maxFlavors: 9, regionRestricted: false },
];

// Flavors Configuration
export const FLAVORS = [
  { name: "Chewing-gum", nameAr: "علكة", color: "320 75% 75%" },
  { name: "Citron", nameAr: "ليمون", color: "52 90% 70%" },
  { name: "Fraise", nameAr: "فراولة", color: "350 85% 75%" },
  { name: "Pêche", nameAr: "خوخ", color: "25 90% 75%" },
  { name: "Chocolat", nameAr: "شوكولاتة", color: "25 45% 45%" },
  { name: "Orange", nameAr: "برتقال", color: "30 95% 65%" },
  { name: "Framboise", nameAr: "توت العليق", color: "340 85% 70%" },
  { name: "Vanille", nameAr: "فانيليا", color: "45 30% 85%" },
  { name: "Pistache", nameAr: "فستق", color: "100 40% 65%" },
  { name: "Caramel", nameAr: "كراميل", color: "35 60% 60%" },
  { name: "Café", nameAr: "قهوة", color: "30 30% 40%" },
  { name: "Abricot", nameAr: "مشمش", color: "28 80% 70%" },
];

// Cities Configuration with Delivery Info
export const CITIES = [
  { name: "Agadir", nameAr: "أكادير", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 35 },
  { name: "Agourai", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Ain Aicha", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Ain Atiq", nameAr: "عين عتيق", deliveryHours: 24, inSaleRabatRegion: true, deliveryPrice: 35 },
  { name: "Ain baida", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Ain Cheggag", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Ain Chekaf - Fes", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "AIn El Aouda", nameAr: "", deliveryHours: 24, inSaleRabatRegion: true, deliveryPrice: 35 },
  { name: "Ain Harouda casa", nameAr: "عين حرودة الدار البيضاء", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Ain Jiri - Meknes", nameAr: "عين جيري - مكناس", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Ain Kansara", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Ain leuh", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Ain Mediouna - Taounate", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Ait Belkacem", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Ait melloul", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Ajdir", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Aknoul", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Al Hoceima", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Anza -AGADIR", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "AOURIR", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Azilal", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Azrou", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 35 },
  { name: "azrou", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "beni mellal", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Benslimane", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Berkane", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Bouderbala", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Boufakrane", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Bouknadel", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 25 },
  { name: "Boulmane", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Bouznika", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 35 },
  { name: "Cabo Negro", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "casablanca", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 35 },
  { name: "Chefchaouen", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Deroua", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Diabat", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "EL BARAKA - MEKNES", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "El-ouidane (MARRAKECH)", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Eljadida", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 35 },
  { name: "Eloualidia -eljadida", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Essaouira", nameAr: "الصويرة", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Fes", nameAr: "فاس", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 35 },
  { name: "Fnideq", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Fquih Ben Salah", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Ghazoua", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "had draa", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "had ouled fraj", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "HANCHANE-ESSA", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Harhoura", nameAr: "الهرهورة", deliveryHours: 24, inSaleRabatRegion: true, deliveryPrice: 30 },
  { name: "Ifrane", nameAr: "إفران", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Ifrn atlas saghir", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Inzegane", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Jamaat shaim", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "JORF LASFAR", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "kenitra", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 30 },
  { name: "Khemissat", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 35 },
  { name: "KHENIFRA zone bni mallal", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Ksar El Kebir", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Ksar Seghir", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Larache", nameAr: "العرائش", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Maaziz", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Marrakech", nameAr: "مراكش", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 35 },
  { name: "Martil", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 35 },
  { name: "MEJJAT - Meknes", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Mejji-essaouira", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Meknes", nameAr: "مكناس", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 35 },
  { name: "Mernissa", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Missour", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Mograne -KENITRA", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 25 },
  { name: "Moulay Bousselham", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Moulay Idriss Zerhoun", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "MOULAY YAACOUB", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Ouazzane", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Oued Amlil", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Ouisslan", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Oulad Tayeb - Fes", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "OULMES", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Ounagha", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Outat el Haj", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "RABAT", nameAr: "", deliveryHours: 24, inSaleRabatRegion: true, deliveryPrice: 25 },
  { name: "rahma", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Ras El Ma-FES", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Ribate El Kheir", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Romani", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Safi", nameAr: "آسفي", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Sahel Boutaher - Taounate", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Sala Al jadida", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 20 },
  { name: "Sale", nameAr: "سلا", deliveryHours: 24, inSaleRabatRegion: true, deliveryPrice: 20 },
  { name: "Sebt Gzoula", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Sebt Mtiwa", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Sefrou", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Senhaja - Sefrou", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Settat", nameAr: "سطات", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "sidi addi", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Sidi allal bahraoui", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 35 },
  { name: "Sidi Bouzid", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "SIDI HRAZEM", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Sidi kacem", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Sidi rahal -CASA", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Skhirat", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 30 },
  { name: "Smimou", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Soualem", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "SOUK EL GOUR", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Taddart - Taza", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Taghazout", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Tahla zone fes", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "TAMANAR zone el jadida", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Tamaris", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Tamesna", nameAr: "تامسنا", deliveryHours: 24, inSaleRabatRegion: true, deliveryPrice: 35 },
  { name: "Tanger", nameAr: "طنجة", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 35 },
  { name: "Taounate", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Taza", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Temara", nameAr: "تمارة", deliveryHours: 24, inSaleRabatRegion: true, deliveryPrice: 25 },
  { name: "Tetouan", nameAr: "تطوان", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 35 },
  { name: "Thar Es-Souk", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Tiddas", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Tiflet", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 35 },
  { name: "Tit mellil", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Tizi Ouasli", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Youssoufia", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Zrizer", nameAr: "", deliveryHours: 24, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Ain taoujdate", nameAr: "", deliveryHours: 48, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Dakhla", nameAr: "الداخلة", deliveryHours: 48, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Guelmim", nameAr: "كلميم", deliveryHours: 48, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Laayoune", nameAr: "العيون", deliveryHours: 48, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Merzouga", nameAr: "مرزوكة", deliveryHours: 48, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Midelt", nameAr: "ميدلت", deliveryHours: 48, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Nador", nameAr: "الناظور", deliveryHours: 48, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Ouarzazate", nameAr: "ورزازات", deliveryHours: 48, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Oujda", nameAr: "وجدة", deliveryHours: 48, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "SAAIDIA zone oujda", nameAr: "", deliveryHours: 48, inSaleRabatRegion: false, deliveryPrice: 39 },
  { name: "Tan-Tan", nameAr: "طانطان", deliveryHours: 48, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Tiznit zone agadir", nameAr: "", deliveryHours: 48, inSaleRabatRegion: false, deliveryPrice: 40 },
  { name: "Zagora", nameAr: "زاكورة", deliveryHours: 48, inSaleRabatRegion: false, deliveryPrice: 40 },
];

// Helper function to get city by name
export const getCityByName = (cityName) => {
  return CITIES.find(city => city.name === cityName);
};

// Helper function to get box size configuration
export const getBoxSize = (pieces) => {
  return BOX_SIZES.find(box => box.pieces === pieces);
};

// Helper function to get flavor by name
export const getFlavorByName = (flavorName) => {
  return FLAVORS.find(flavor => flavor.name === flavorName);
};